name: Deploy static HTML to GitHub Pages branch sites

on:
  push:
    branches:
      - main  # Cambia esto si usas otra rama principal

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Deploy a GitHub Pages (custom branch)
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
          publish_branch: sites  # <- Aquí especificamos que use la rama 'sites'