name: Comenta en main/develop 

on:
  pull_request:
    types: [opened]
    branches: [main, develop]
  push:
    branches: [main, develop]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comentar en PR o Push a main/develop
        uses: actions/github-script@v7
        with:
          script: |
            const message = context.eventName === 'push'
              ? "📌 Se ha realizado un push a `" + context.ref.replace('refs/heads/', '') + "`."
              : "🚀 Gracias por tu Pull Request hacia `" + context.payload.pull_request.base.ref + "`. El equipo lo revisará pronto. 🙌";

            const issue_number = context.issue?.number || context.payload.pull_request?.number;

            if (issue_number) {
              github.rest.issues.createComment({
                issue_number,
                owner: context.repo.owner,
                repo: context.repo.repo,
                body: message
              });
            } else {
              console.log("No se pudo comentar: No hay issue_number disponible.");
            }
